dist: trusty
sudo: required
language: node_js
node_js:
  - "4"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  #- npm run lint
  - npm run test-once 
  #- npm run e2e

after_script:
  - python html2text.py target/site/surefire-report.html

notifications:
  email: false